[features]
skip-lint = true

[programs.localnet]
crowdfunding = "BkBYehfNc7WBa6MmmFz3mMzwBduQLBTzboA3e6JaBGYR"

[test]
startup_wait = 30000

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
