[features]
skip-lint = true

[programs.localnet]
crowdfunding = "Gf3bXGS7iA2EUxzXs1xS6qwZBPGS8idyqMNitQ5NKDSA"

[test]
startup_wait = 30000

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
